-- Sinh tự động bởi scripts/sso-management/generate-baseline.js từ build_management (26/09/2026).
-- Bảng user/tổ chức/nhóm quyền + bảng a_* của SSO (không có country, không có rank_weight).
-- Chạy trên DB sso_management rỗng. Đã commit thì KHÔNG sinh lại đè lên - đổi schema bằng file mới.

CREATE TABLE IF NOT EXISTS public.system_users (
  user_id character varying(36) NOT NULL,
  user_name character varying(150) NOT NULL,
  password character varying(250) NOT NULL,
  type character varying(150) DEFAULT NULL::character varying,
  description character varying(250) DEFAULT NULL::character varying,
  online_flag smallint,
  active_flag integer NOT NULL,
  created_by_user_id character varying(36) NOT NULL,
  created_date_time timestamp without time zone NOT NULL,
  lu_updated timestamp without time zone,
  lu_user_id character varying(36) DEFAULT NULL::character varying,
  CONSTRAINT system_users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_profiles (
  user_id character varying(250) NOT NULL,
  first_name character varying(20) DEFAULT NULL::character varying,
  middle_name character varying(20) DEFAULT NULL::character varying,
  last_name character varying(20) DEFAULT NULL::character varying,
  full_name character varying(60) DEFAULT NULL::character varying,
  avatar character varying(250) DEFAULT NULL::character varying,
  gender smallint,
  date_of_birth date,
  email character varying(150) DEFAULT NULL::character varying,
  phone_number character varying(20) DEFAULT NULL::bpchar,
  active_flag integer NOT NULL,
  created_by_user_id character varying(36) NOT NULL,
  created_date_time timestamp without time zone NOT NULL,
  lu_updated timestamp without time zone,
  lu_user_id character varying(36) DEFAULT NULL::character varying,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_profiles_ibfk_1 FOREIGN KEY (user_id) REFERENCES system_users(user_id)
);
CREATE INDEX IF NOT EXISTS user_id ON public.user_profiles USING btree (user_id);

CREATE TABLE IF NOT EXISTS public.branch (
  branch_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  branch_name character varying(250) NOT NULL,
  phone character varying(36) DEFAULT NULL::character varying,
  fax character varying(36) DEFAULT NULL::character varying,
  address character varying(250) DEFAULT NULL::character varying,
  active_flag integer NOT NULL,
  created_by_user_id character varying(36) NOT NULL,
  created_date_time timestamp without time zone NOT NULL,
  lu_updated timestamp without time zone,
  lu_user_id character varying(36) DEFAULT NULL::character varying,
  CONSTRAINT branch_pkey PRIMARY KEY (branch_id)
);

CREATE TABLE IF NOT EXISTS public.department (
  department_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  department_name character varying(250) NOT NULL,
  phone character varying(36) DEFAULT NULL::character varying,
  fax character varying(36) DEFAULT NULL::character varying,
  address character varying(250) DEFAULT NULL::character varying,
  active_flag integer NOT NULL,
  created_by_user_id character varying(36) NOT NULL,
  created_date_time timestamp without time zone NOT NULL,
  lu_updated timestamp without time zone,
  lu_user_id character varying(36) DEFAULT NULL::character varying,
  CONSTRAINT department_pkey PRIMARY KEY (department_id)
);

CREATE TABLE IF NOT EXISTS public.positions (
  position_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  position_name character varying(250) NOT NULL,
  description character varying(500) DEFAULT NULL::character varying,
  active_flag integer NOT NULL,
  created_by_user_id character varying(36) NOT NULL,
  created_date_time timestamp without time zone NOT NULL,
  lu_updated timestamp without time zone,
  lu_user_id character varying(36) DEFAULT NULL::character varying,
  CONSTRAINT positions_pkey PRIMARY KEY (position_id)
);

CREATE TABLE IF NOT EXISTS public.employee (
  employee_id character varying(36) NOT NULL,
  fullname character varying(250) NOT NULL,
  phone_number character varying(36) NOT NULL,
  email character varying(250) NOT NULL,
  position_id integer NOT NULL,
  department_id integer NOT NULL,
  branch_id integer NOT NULL,
  active_flag integer NOT NULL,
  created_by_user_id character varying(36) NOT NULL,
  created_date_time timestamp without time zone NOT NULL,
  lu_updated timestamp without time zone,
  lu_user_id character varying(36) DEFAULT NULL::character varying,
  CONSTRAINT employee_pkey PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS public.roles (
  role_id character varying(36) NOT NULL,
  role_code character varying(50) NOT NULL,
  role_name character varying(250) DEFAULT NULL::character varying,
  description character varying(250) DEFAULT NULL::character varying,
  active_flag integer NOT NULL,
  created_by_user_id character varying(36) NOT NULL,
  created_date_time timestamp without time zone NOT NULL,
  lu_updated timestamp without time zone,
  lu_user_id character varying(36) DEFAULT NULL::character varying,
  CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS public.user_roles (
  user_role_id character varying(36) NOT NULL,
  user_id character varying(36) NOT NULL,
  role_id character varying(36) NOT NULL,
  active_flag integer NOT NULL,
  created_by_user_id character varying(36) NOT NULL,
  created_date_time timestamp without time zone NOT NULL,
  lu_updated timestamp without time zone,
  lu_user_id character varying(36) DEFAULT NULL::character varying,
  CONSTRAINT user_roles_pkey PRIMARY KEY (user_role_id),
  CONSTRAINT user_roles_ibfk_1 FOREIGN KEY (user_id) REFERENCES system_users(user_id),
  CONSTRAINT user_roles_ibfk_2 FOREIGN KEY (role_id) REFERENCES roles(role_id)
);
CREATE INDEX IF NOT EXISTS user_roles_role_id_index ON public.user_roles USING btree (role_id);
CREATE INDEX IF NOT EXISTS user_roles_user_id_index ON public.user_roles USING btree (user_id);

CREATE TABLE IF NOT EXISTS public.a_session (
  session_id character varying(36) NOT NULL,
  user_id character varying NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  revoked_at timestamp with time zone,
  user_agent character varying(512),
  ip character varying(64),
  remember boolean DEFAULT false NOT NULL,
  CONSTRAINT a_session_pkey PRIMARY KEY (session_id),
  CONSTRAINT a_session_user_id_fkey FOREIGN KEY (user_id) REFERENCES system_users(user_id)
);
CREATE INDEX IF NOT EXISTS idx_a_session_cleanup_expires ON public.a_session USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_a_session_cleanup_revoked ON public.a_session USING btree (revoked_at) WHERE (revoked_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_a_session_user_id ON public.a_session USING btree (user_id);

CREATE TABLE IF NOT EXISTS public.a_refresh_token (
  jti character varying(36) NOT NULL,
  session_id character varying(36) NOT NULL,
  user_id character varying NOT NULL,
  issued_at timestamp with time zone DEFAULT now() NOT NULL,
  expires_at timestamp with time zone NOT NULL,
  rotated_to character varying(36),
  revoked_at timestamp with time zone,
  CONSTRAINT a_refresh_token_pkey PRIMARY KEY (jti),
  CONSTRAINT a_refresh_token_session_id_fkey FOREIGN KEY (session_id) REFERENCES a_session(session_id),
  CONSTRAINT a_refresh_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES system_users(user_id)
);
CREATE INDEX IF NOT EXISTS idx_a_refresh_token_cleanup_expires ON public.a_refresh_token USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_a_refresh_token_cleanup_revoked ON public.a_refresh_token USING btree (revoked_at) WHERE (revoked_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_a_refresh_token_session_id ON public.a_refresh_token USING btree (session_id);

CREATE TABLE IF NOT EXISTS public.a_password_reset_token (
  token_hash character varying(64) NOT NULL,
  user_id character varying NOT NULL,
  created_at timestamp without time zone DEFAULT now() NOT NULL,
  expires_at timestamp without time zone NOT NULL,
  used_at timestamp without time zone,
  CONSTRAINT a_password_reset_token_pkey PRIMARY KEY (token_hash),
  CONSTRAINT a_password_reset_token_user_id_fkey FOREIGN KEY (user_id) REFERENCES system_users(user_id)
);
CREATE INDEX IF NOT EXISTS idx_a_password_reset_cleanup_expires ON public.a_password_reset_token USING btree (expires_at);
CREATE INDEX IF NOT EXISTS idx_a_password_reset_cleanup_used ON public.a_password_reset_token USING btree (used_at) WHERE (used_at IS NOT NULL);
CREATE INDEX IF NOT EXISTS idx_a_password_reset_token_user_id ON public.a_password_reset_token USING btree (user_id);

CREATE TABLE IF NOT EXISTS public.a_app (
  app_id character varying(36) NOT NULL,
  app_key character varying(50) NOT NULL,
  app_name character varying(150) NOT NULL,
  description character varying(250),
  url character varying(500) DEFAULT ''::character varying NOT NULL,
  color character varying(9) DEFAULT '#2563a6'::character varying NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  active_flag integer DEFAULT 1 NOT NULL,
  created_by_user_id character varying(36) NOT NULL,
  created_date_time timestamp without time zone DEFAULT now() NOT NULL,
  lu_user_id character varying(36),
  lu_updated timestamp without time zone,
  icon character varying(500),
  CONSTRAINT a_app_pkey PRIMARY KEY (app_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_a_app_key_active ON public.a_app USING btree (app_key) WHERE (active_flag = 1);

CREATE TABLE IF NOT EXISTS public.a_app_access (
  app_id character varying(36) NOT NULL,
  user_id character varying NOT NULL,
  created_by_user_id character varying(36) NOT NULL,
  created_date_time timestamp without time zone DEFAULT now() NOT NULL,
  CONSTRAINT a_app_access_pkey PRIMARY KEY (app_id, user_id),
  CONSTRAINT a_app_access_app_id_fkey FOREIGN KEY (app_id) REFERENCES a_app(app_id),
  CONSTRAINT a_app_access_user_id_fkey FOREIGN KEY (user_id) REFERENCES system_users(user_id)
);
CREATE INDEX IF NOT EXISTS idx_a_app_access_user_id ON public.a_app_access USING btree (user_id);
